import React, { FunctionComponent } from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import { MessageProvider, setDefaultTitle } from "./lib";
import { LayoutProvider } from "./lib/layout/contexts/layout-context";
import DynamicLoadComponent from "./lib/layout/utils/dynamicLoadComponent";
import { GyudAccessProvider } from "./lib/access-context";

const a = React.memo(() => {
  return <>123</>;
});

const menus = [
  {
    main: true,
    key: "main",
    group: "main",
    title: "통합조회",
    iconName: "chart-simple",
    component: a,
    visible: true,
  },
  {
    key: "masterData",
    group: "masterData",
    title: "기준정보",
    iconName: "database",
    children: [
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "users",
        shortKey: "usr",
        group: "masterData",
        title: "사원관리",
        visible: true,
      },
    ],
  },
  {
    key: "delivery",
    group: "delivery",
    title: "납품관리",
    iconName: "truck",
    children: [
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
      {
        key: "product",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        hasClose: true,
        component: App,
        visible: true,
      },
      {
        key: "product2",
        shortKey: "prd",
        group: "masterData",
        title: "품목관리",
        component: App,
        visible: true,
      },
    ],
  },
];

const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);

setDefaultTitle("asd");
root.render(
  <React.StrictMode>
    <GyudAccessProvider>
      <MessageProvider>
        <LayoutProvider menus={menus} statics={["static"]}>
          <App />
        </LayoutProvider>
      </MessageProvider>
    </GyudAccessProvider>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
